In [17]:
import sys
import time
from Env.simUtils import *

import grpc

host = '127.0.0.1:30001'
scene_num = 1
map_id = 1
server = SimServer(host,scene_num = scene_num, map_id = map_id)
# sim=SimAction(host,scene_id=0)

In [20]:
joints = [0]*21
# 36.0, -40.0, 40.0, -90.0, 5.0
joints[-7]=36
joints[-6]=-40
joints[-5]=40
joints[-4]=-90
action = GrabSim_pb2.Action(scene=0, action=GrabSim_pb2.Action.ActionType.RotateJoints, values=joints)
message = server.sim_client.Do(action)

In [20]:
for action in sim.graspTargetObj(obj_id=1,handSide='Right'):
    print(action)


KeyboardInterrupt



In [17]:
scene=sim.removeObjects([0])

In [14]:
sim.initState()

In [10]:
sim.genObjs(n=2,ids=[23,12],h=sim.desk_height,handSide='Right')

[[23, -36.611615022650334, -6.516443952108732, 99, 0, 0, 0, 1, 1, 0.1],
 [12, -45.727392584337984, -19.07782631613668, 99, 0, 0, 0, 0.9, 0.9, 0.9]]

In [8]:
handSide='Right'
objs=[]
ids=[23,12]
objs_loc = generate_points_in_square(2,sim.target_range[handSide],sim.obj_range)
# assert len(objs_loc)==n, 'generated obj number less than needed'
for id,loc in zip(ids,objs_loc):
    objs.append([id,loc[0],loc[1],sim.desk_height+1,0,0,0])
objs[0]+=[1,1,1]
scene=sim.addObjects(objs,location='relatively')

In [7]:
sim.registry_objs

[None,
 ([79.93091583251953, -6.516443729400635, 107.5], 9.5),
 ([70.81513977050781, -19.07782554626465, 104.76000213623047],
  6.760002136230469)]

In [ ]:
for action in sim.graspTargetObj(1,handSide=handSide):
    print(action)

In [17]:
sim.desk_height

98

In [27]:
sim.addDesk(0,h=98)
sim.genObjs(n=1,ids=21)

[[21, -35.515519503881606, 0.20993370291152758, 91, 0, 0, 0, 1, 1, 1]]

In [17]:
sim.initState()

In [16]:
sim.getActuators()

array([-1.93231013e-02, -9.72418900e+01,  3.47298455e+00,  1.10487856e-01,
        1.09054886e-01,  1.14364848e-01,  1.07733972e-01, -5.23531227e+01,
        2.18624554e+01,  3.31822746e-02,  8.24994445e-02, -2.19020080e-02,
       -1.86436065e-03, -4.68058527e-01,  6.44119456e-02,  1.78142592e-01,
        3.55328827e+01, -4.16607218e-04, -1.87331636e-03, -9.86356964e+01,
       -2.03312588e+00, -5.72957850e+00, -5.72957850e+00, -5.72957802e+00,
       -5.72957850e+00, -5.13900146e+01, -2.02540779e+01, -5.72957850e+00,
        3.00003681e+01, -5.12255764e+00, -2.58070774e+01])

In [27]:
sim.bow_head()

array([ 4.77197500e-06, -9.88900604e+01,  4.87631130e+00, -2.97053647e+00,
       -3.30658269e+00, -3.21994472e+00, -3.31820560e+00, -5.18201370e+01,
        2.05184231e+01, -5.67035103e+00,  3.00003109e+01,  6.81182146e+00,
        2.23985291e+01, -6.93456054e-01,  1.25737593e-01, -3.67542985e-03,
        3.50000000e+01,  4.01720032e-03, -7.13843340e-03, -1.00429947e+02,
       -4.01931143e+00, -5.21705389e+00, -5.42529583e+00, -5.42487383e+00,
       -5.42526245e+00, -5.10496826e+01, -2.04081345e+01, -5.51246071e+00,
        3.00003586e+01, -5.12636852e+00, -2.58006687e+01])

In [22]:
sim.changeJoints(sim.getActuators())

In [10]:
sim.getSensorsData('All')

[[0.01542260420424665,
  -0.21394757358365274,
  -0.07845196120893669,
  -0.973567598484922],
 [-0.016763314911993125,
  0.05804673052406484,
  -0.0035690033948650437,
  0.9981667348511448],
 [88.9417724609375, 20.199615478515625, 131.44737243652344],
 [91.9306640625, -12.647750854492188, 102.03794860839844],
 [78.608642578125, 18.698989868164062, 139.7353973388672],
 [76.24990844726562, 18.548248291015625, 140.8222198486328],
 [73.8843994140625, 18.628341674804688, 141.8950958251953],
 [77.38320922851562, 18.708892822265625, 138.31126403808594],
 [75.02487182617188, 18.568374633789062, 139.39759826660156],
 [72.6583251953125, 18.668853759765625, 140.4691162109375],
 [76.90609741210938, 18.383453369140625, 134.1462860107422],
 [74.54766845703125, 18.244125366210938, 135.23170471191406],
 [72.18133544921875, 18.342666625976562, 136.3046112060547],
 [77.386474609375, 18.513916015625, 136.34097290039062],
 [75.02798461914062, 18.374160766601562, 137.4263458251953],
 [72.66162109375, 18.47

In [31]:
success_num = 0
np.random.seed(42)
can_list = sim.can_list
handSide = 'Right'
for _,id in enumerate(can_list):
    sim.reset()
    sim.addDesk(random.choice(list(sim.desks.ID.values)),h=98)
    n_objs = 2
    ids = random.sample(list(can_list),n_objs)
    sim.genObjs(n=n_objs,ids=[24,12],h=sim.desk_height,handSide=handSide)
    for action in sim.graspTargetObj(1,handSide=handSide,gap=1):
        print(action)
        # sim.bow_head()

    time.sleep(0.5)
    if sim.checkGraspTargetObj(1):
        print('success')
        success_num+=1
    print(f'success rate:{success_num}/{_+1}')
    
    # obj1 = sim.getObjsInfo()[1]['location']
    # obj2 = sim.getObjsInfo()[2]['location']
    # if handSide=='Right':
    #     if obj1[1]<obj2[1]:
    #         obj1_id,obj2_id = 1,2
    #     else:
    #         obj1_id,obj2_id = 2,1
    # else:
    #     if obj1[1]>obj2[1]:
    #         obj1_id,obj2_id = 1,2
    #     else:
    #         obj1_id,obj2_id = 2,1


[0, 0, 0, 0.004089642422405781, 0.4032956962782878, -1.0, 0, 0]
[0, 0, 0, 0.0086011944654795, 0.41485374004234976, -1.0, 0, 0]
[0, 0, 0, 0.016037738344888648, 0.44757429345324284, -1.0, 0, 0]
[0, 0, 0, 0.02101006608006484, 0.45357312146506146, -1.0, 0, 0]
[0, 0, 0, 0.025231598678958703, 0.44596751231340387, -1.0, 0, 0]
[0, 0, 0, 0.029546787561777657, 0.44893947351974, -1.0, 0, 0]
[0, 0, 0, 0.03439203903000693, 0.4635750146145649, -1.0, 0, 0]
[0, 0, 0, 0.03939978028005928, 0.4753814110542349, -1.0, 0, 0]
[0, 0, 0, 0.04347682389784892, 0.4797094601030234, -1.0, 0, 0]
[0, 0, 0, 0.04927551327703954, 0.4872227518730119, -1.0, 0, 0]
[0, 0, 0, 0.054089562049488074, 0.4953576034158135, -1.0, 0, 0]
[0, 0, 0, 0.05853231011977336, 0.5047941260847737, -1.0, 0, 0]
[0, 0, 0, 0.06402483492892612, 0.5168732746493337, -1.0, 0, 0]
[0, 0, 0, 0.06943745563005477, 0.5269450902005784, -1.0, 0, 0]
[0, 0, 0, 0.07400285477127418, 0.5389231081218211, -1.0, 0, 0]
[0, 0, 0, 0.07913321964813043, 0.5530172191490247

KeyboardInterrupt: 

In [1]:
jointInOrder = ['knee', 'lumbar_yaw', 'lumbar_pitch','lumbar_roll', 'neck_yaw', 'neck_pitch', 'neck_roll', 'left_shoulder_pitch', 'left_shoulder_roll',
  'left_elbow_yaw', 'left_elbow_pitch', 'left_wrist_yaw', 'left_wrist_pitch', 'left_wrist_roll', 'right_shoulder_pitch',
  'right_shoulder_roll', 'right_elbow_yaw', 'right_elbow_pitch', 'right_wrist_yaw', 'right_wrist_pitch', 'right_wrist_roll', 
  'left_thumb', 'left_index', 'left_middle', 'left_ring', 'left_pinky', 'right_thumb', 'right_index', 'right_middle', 'right_ring', 'right_pinky']

In [6]:
import numpy
a=[1,2]

In [7]:
a[:1],a[1:] = a[1:], a[:1]

In [8]:
a

[2, 1]

In [6]:
sim.checkGraspTargetObj(1)

True

In [3]:
can_list

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25], dtype=int64)

In [3]:
sim.addDesk(0,98)

In [11]:
sim.initState()

In [13]:
scene=sim.removeObjects([1])

In [14]:
handSide='Left'
objs=[]
ids=[22]
objs_loc = generate_points_in_square(1,sim.target_range[handSide],sim.obj_range)
# assert len(objs_loc)==n, 'generated obj number less than needed'
for id,loc in zip(ids,objs_loc):
    objs.append([id,-46.11830028-12,-3.43694289,sim.desk_height+1,0,0,-90,0.2,0.2,0.2])
scene=sim.addObjects(objs,location='relatively')
sim.sim_client.SetObjectJointAngle(GrabSim_pb2.ObjectJointCtrl(scene=0,objectId=1,jointName="joint_door",angle=-30))

In [5]:
for action in sim.closeDoor(obj_id=1):
    print(action)

[-0.005665249294708019, -0.03892119725545129, -0.9971968332926338, 0, 0, 0, 0, 0]
[0.023429022894958962, -0.05951658884684363, -1.493996938069671, 0, 0, 0, 0, 0]
[0.017763773600265154, -0.09843778610229492, -2.4911937713623047, 0, 0, 0, 0, 0]
[0.010023328993057135, -0.1281274159749337, -3.2434260050455777, 0, 0, 0, 0, 0]
[0.06295182969834912, -0.10593716303507605, -2.6503823598225864, 0, 0, 0, 0, 0]
[0.057286580403641096, -0.14485836029052734, -3.6475791931152344, 0, 0, 0, 0, 0]
[0.04319847954644729, -0.16055568059285363, -3.99656740824382, 0, 0, 0, 0, 0]
[0.03704494900173927, -0.10552851359049598, -2.6313298543294223, 0, 0, 0, 0, 0]
[0.03137969970703125, -0.14444971084594727, -3.6285266876220703, 0, 0, 0, 0, 0]
[-0.005596584743926769, -0.14624627431233606, -3.689406077067062, 0, 0, 0, 0, 0]
[0.003600226508240212, -0.1117421785990409, -2.7811921437581333, 0, 0, 0, 0, 0]
[-0.0020650227864535964, -0.1506633758544922, -3.7783889770507812, 0, 0, 0, 0, 0]
[-0.0077302720811616155, -0.1895845

In [7]:
sim.checkCloseDoor(1)

False

In [9]:
sim.getObservation()

location {
  X: 116.54253387451172
}
rotation {
  Yaw: 180.0
}
joints {
  name: "joint_knee"
  angle: 0.002824622206389904
}
joints {
  name: "joint_left_elbow_pitch"
  angle: -76.44937896728516
}
joints {
  name: "joint_left_elbow_yaw"
  angle: -15.725418090820312
}
joints {
  name: "joint_left_index1"
  angle: -5.150472640991211
}
joints {
  name: "joint_left_index2"
  angle: -5.023436546325684
}
joints {
  name: "joint_left_index3"
  angle: -5.014880180358887
}
joints {
  name: "joint_left_middle1"
  angle: -5.204717636108398
}
joints {
  name: "joint_left_middle2"
  angle: -5.460830211639404
}
joints {
  name: "joint_left_middle3"
  angle: -5.198370456695557
}
joints {
  name: "joint_left_pinky1"
  angle: -5.73148250579834
}
joints {
  name: "joint_left_pinky2"
  angle: -5.731024742126465
}
joints {
  name: "joint_left_pinky3"
  angle: -4.496458053588867
}
joints {
  name: "joint_left_ring1"
  angle: -5.221477508544922
}
joints {
  name: "joint_left_ring2"
  angle: -5.3188939094543

In [99]:
sim.get

In [9]:
import pickle
with open('../../tmp/000001.pkl','rb') as f:
    data=pickle.load(f)

In [18]:
import hashlib
def string_to_seed(input_string):
    hash_object = hashlib.sha256(input_string.encode())
    hex_dig = hash_object.hexdigest()
    # 将哈希值转换为整数
    seed = int(hex_dig, 16)%100000009
    return seed

In [19]:
string_to_seed('ssss')

87093454

In [29]:
for frame in data['trajectory']:
    print(frame['action'])

[0, 0, 0, -0.13462923102415997, 0.34098616844861535, -1.0]
[0, 0, 0, -0.12645306224888567, 0.34003531534093534, -1.0]
[0, 0, 0, -0.11619961478587988, 0.35697672733430086, -1.0]
[0, 0, 0, -0.10603254541359797, 0.37720307161716016, -1.0]
[0, 0, 0, -0.0972640536397813, 0.39185074339487846, -1.0]
[0, 0, 0, -0.08882878239188885, 0.4076937288056822, -1.0]
[0, 0, 0, -0.08029414784508832, 0.42698109597609946, -1.0]
[0, 0, 0, -0.07232920122258708, 0.44529278300144653, -1.0]
[0, 0, 0, -0.06486445103195665, 0.46498045931672116, -1.0]
[0, 0, 0, -0.05765594825591709, 0.48880823502708554, -1.0]
[0, 0, 0, -0.051393541354723966, 0.5119535280266475, -1.0]
[0, 0, 0, -0.045647085773279826, 0.5394693010962942, -1.0]
[0, 0, 0, -0.041067641675655776, 0.5665159282357172, -1.0]
[0, 0, 0, -0.03779573374492521, 0.5855477918609712, -1.0]
[0, 0, 0, -0.03651836045667607, 0.5993018498963283, -1.0]
[0, 0, 0, -0.037063308787272264, 0.6149125262431471, -1.0]
[0, 0, 0, -0.03962924454969153, 0.629287720857618, -1.0]
[0,

In [ ]:
GrabSim_pb2.ObjectJointCtrl

In [10]:
sim.genObjs(n=1,ids=22,h=sim.desk_height)

[[22, -47.65972039336345, -16.100136991594933, 101, 0, 0, 0, 1, 1, 1]]

In [4]:
success_num = 0
np.random.seed(42)
can_list = sim.can_list
handSide = 'Right'
for _ in range(5):
    sim.reset()
    sim.addDesk(0,h=98)
    n_objs = 1 
    ids = random.sample(can_list,n_objs)
    sim.genObjs(n=n_objs,ids=ids,h=sim.desk_height,handSide=handSide)
    obj_id = 1

    for action in sim.pushLeft(obj_id,handSide=handSide):
        pass
    time.sleep(1)
    if sim.checkPushLeft(obj_id):
        print('success')
        success_num+=1
    print(f'success rate:{success_num}/{_+1}')
    
    # obj1 = sim.getObjsInfo()[1]['location']
    # obj2 = sim.getObjsInfo()[2]['location']
    # if handSide=='Right':
    #     if obj1[1]<obj2[1]:
    #         obj1_id,obj2_id = 1,2
    #     else:
    #         obj1_id,obj2_id = 2,1
    # else:
    #     if obj1[1]>obj2[1]:
    #         obj1_id,obj2_id = 1,2
    #     else:
    #         obj1_id,obj2_id = 2,1


success
success rate:1/1


KeyboardInterrupt: 

In [6]:
sim.checkKnockOver(obj_id)

True

In [5]:
obj_loc=np.array(sim.findObj(id=obj_id)['location'])
sim.desk_height+sim.registry_objs[obj_id][1]/2>obj_loc[-1]


True

In [4]:
initLoc = sim.registry_objs[obj_id][0]
nowLoc = sim.getObjsInfo()[obj_id]['location']
nowLoc[0]-initLoc[0]

-2.81524658203125

In [5]:
if sim.checkMoveNear(obj1_id=obj1_id,obj2_id=obj2_id):
    print('success')
    success_num+=1

success


In [4]:
obj1_loc = np.array(sim.getObjsInfo()[obj1_id]['location'])
obj2_loc = np.array(sim.getObjsInfo()[obj2_id]['location'])
np.linalg.norm(obj2_loc-obj1_loc)

7.067946871786117

In [5]:
sim.registry_objs

[None, None, None, 6.760002136230469]

In [11]:
success_num = 0
np.random.seed(42)
can_list = sim.can_list
handSide = 'Right'
for _ in range(1):
    sim.reset()
    sim.removeObjects()
    sim.addDesk(0,h=98)
    ids = random.choice(can_list)
    sim.genObjs(n=1,ids=18,h=sim.desk_height,handSide=handSide)
    method='absolute'
    obj_id=1
    gap=1.5
    keep_rpy=(0,0,0)
    time_step=0
    if handSide=='Right':
        target_oringin_loc=sim.getObjsInfo()[1]['location']
        for action in sim.closeTargetObj(1,return_action=True):
            time.sleep(0.1)
            st=time.time()
            mat = sim.getImage()
            # print(action)
            time_step+=1
        sim.grasp()
        for action in sim.moveHandReturnAction(0,0,10,gap=1):
            mat = sim.getImage()
            time.sleep(0.1)
        target_now_loc=sim.getObjsInfo()[1]['location']
        print('time_step:',time_step)
        if target_now_loc[2]-target_oringin_loc[2]>5:
            print('success')
            success_num+=1
        print(f'success rate:{success_num}/{_+1}')
    elif handSide=='Left':
        target_oringin_loc=sim.getObjsInfo()[1]['location']
        obj_loc=np.array(sim.findObj(id=obj_id)['location'])
        obj_loc[0]+=4
        obj_loc[1]+=6
        for i in range(100):  
            time_step+=1
            sensor = sim.getSensorsData(handSide='All',type='full')
            middle = np.array(sensor[-24]['data'])
            p = max(abs(obj_loc-middle))/gap if max(abs(obj_loc-middle))>gap else 1
            vector = (obj_loc-middle)/p
            if max(abs(obj_loc[:2]-middle[:2]))<1 and max(abs(obj_loc[2:]-middle[2:]))<2:
                break
            sim.moveHand(*vector,handSide=handSide,method='diff',gap=gap,keep_rpy=(0,0,0))
        
        obj_loc=np.array(sim.findObj(id=obj_id)['location'])
        obj_loc[0]-=4
        obj_loc[1]+=4
        for i in range(100):
            time_step+=1
            sensor = sim.getSensorsData(handSide='All',type='full')
            middle = np.array(sensor[-24]['data'])
            p = max(abs(obj_loc-middle))/gap if max(abs(obj_loc-middle))>gap else 1
            vector = (obj_loc-middle)/p
            if max(abs(obj_loc[:2]-middle[:2]))<1 and max(abs(obj_loc[2:]-middle[2:]))<2:
                break
            sim.moveHand(*vector,handSide=handSide,method='diff',gap=gap,keep_rpy=(0,0,0))
        sim.grasp(handSide=handSide)
        sim.moveHand(0,0,10,handSide=handSide)
        target_now_loc=sim.getObjsInfo()[1]['location']
        print('time_step:',time_step)
        if target_now_loc[2]-target_oringin_loc[2]>5:
            print('success')


time_step: 38
success
success rate:1/1


In [ ]:
            success_num+=1
        print(f'success rate:{success_num}/{_+1}')

In [12]:
sim.moveHand(0,0,-8,handSide=handSide)

In [6]:
sim.moveHand(5,0,0,handSide=handSide)

In [13]:
sim.release(handSide=handSide)

In [3]:
np.array(sim.getActuators())[[-4,-10,-9,-8,-7]]

array([ 9.81004047, 12.82505035, 27.38894463, 58.87218475, 17.03774452])

In [ ]:
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
import sys
import time
import json

sys.path.append('./')
sys.path.append('../')
from src.Env.simUtils import *
import matplotlib.pyplot as plt
# from moviepy.editor import ImageSequenceClip, ImageClip, concatenate_videoclips

import grpc

print('数据生成脚本启动')

host = '127.0.0.1:30001'
scene_num = 1
map_id = 2
server = SimServer(host, scene_num=scene_num, map_id=map_id)

sim = Sim(host, scene_id=0)

import pickle


import os

output_path = '/data2/liangxiwen/zkd/datasets/dataGen/DATA/1_objs'
data_info="使用中指判断位置"
meta_data_path = output_path + os.sep + 'meta_data.json'
n_objs = 1
handSide = 'Right'
can_list = [12, 14, 16, 17, 18]

from copy import deepcopy
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import random

random.seed(42)


def Resize(mat):
    mat = Image.fromarray(mat, mode='RGB')
    mat = mat.resize((224, 224))
    mat = np.array(mat)
    mat = 1.0 * mat
    mat = mat / 255.0
    return mat


from tqdm import tqdm
collected_num=0
for epoch in range(1):
    print('Epoch:', epoch)
    offline_data = dict()
    for index in tqdm(range(1000)):
        sim.reset()
        sim.bow_head()
        time.sleep(1)
        sim.grasp('release',handSide=handSide)
        time.sleep(1)
        sim.removeObjects('all')
        objs = sim.getObjsInfo()
        scene = sim.removeObjects([0])
        desk_height = 98 # 固定桌子高度
        desk_id = 1
        sim.addDesk(desk_id, h=desk_height)
        obj_id = random.choice(can_list)
        other_obj_ids = random.choices([x for x in sim.objs.ID.values if x != obj_id], k=n_objs - 1)
        ids = [obj_id] + other_obj_ids
        objList = sim.genObjs(n=n_objs, ids=ids, h=sim.desk_height, handSide = handSide)
        target_origin_loc = sim.getObjsInfo()[1]['location']
        obj_id = objList[0][0]
        target_obj = sim.objs[sim.objs.ID == obj_id].Name.values[0]
        sx, sy = sim.getObservation().location.X, sim.getObservation().location.Y

        x = np.random.uniform(-10, 10)
        y = np.random.uniform(-10,10)
        z = np.random.uniform(-2,5)
        sim.moveHand(x,y,z,handSide=handSide, method='diff', keep_rpy=(0, 0, 0))

        ox, oy, oz = sim.getSensorsData(handSide=handSide)[0]
        offline_data['trajectory'] = []
        last_action = (ox-sx, oy-sy, oz)
        last_img = Resize(sim.getImage())
        last_state = sim.getState()
        for action in sim.closeTargetObj(obj_id=1,handSide=handSide,return_action=True):
            # sim.bow_head()
            each_frame = {}
            each_frame['img'] = last_img
            each_frame['state'] = last_state
            each_frame['action'] = (*action, 0)
            time.sleep(0.05)
            last_img = Resize(sim.getImage())
            last_state = sim.getState()
            each_frame['after_state'] = last_state
            offline_data['trajectory'].append(each_frame)

        loc1 = sim.findObj(name=target_obj)['location']
        loc2 = sim.getSensorsData(handSide=handSide)[0]

        # 抓取
        each_frame = {}
        mat = sim.getImage()
        mat = Resize(mat)
        each_frame['img'] = mat
        each_frame['state'] = sim.getState()
        before_grasp_img = sim.getImage()
        sim.grasp(handSide=handSide)
        grasp_img = sim.getImage()
        each_frame['action'] = (0, 0, 0, 0, 0, 0, 1)
        each_frame['after_state'] = sim.getState()
        offline_data['trajectory'].append(each_frame)

        last_img = sim.getImage()
        last_state = sim.getState()
        for action in sim.moveHandReturnAction(0, 0, 15, gap=1.5, method='diff',handSide=handSide):
            # sim.bow_head()
            each_frame = {}
            each_frame['img'] = Resize(last_img)
            each_frame['state'] = last_state
            if handSide=='Right':
                each_frame['action'] = (0, 0, 0, 0, 0, 1, 1)
            else:
                each_frame['action'] = (0, 0, 1, 0, 0, 0, 1)
            state = sim.getState()
            each_frame['after_state'] = state
            offline_data['trajectory'].append(each_frame)
            last_img = sim.getImage()
            last_state = state

        target_now_loc = sim.getObjsInfo()[1]['location']
        if target_now_loc[2] - target_origin_loc[2] > 10:
            collected_num += 1
            is_success = True
            print(f'Success have collected {collected_num} datas')
        else:
            is_success = False
            print('fail data:', index, desk_id, obj_id, objList)


数据生成脚本启动
Epoch: 0


  0%|          | 1/1000 [00:30<8:32:14, 30.76s/it]

Success have collected 1 datas


  0%|          | 2/1000 [01:02<8:40:38, 31.30s/it]

Success have collected 2 datas


  0%|          | 3/1000 [01:31<8:24:05, 30.34s/it]

Success have collected 3 datas


  0%|          | 4/1000 [02:03<8:34:56, 31.02s/it]

Success have collected 4 datas


  0%|          | 5/1000 [02:34<8:31:35, 30.85s/it]

fail data: 4 1 14 [[14, -44.76185638081009, -1.8511080282440169, 99, 0, 0, 0, 0.9, 0.9, 0.9]]


  1%|          | 6/1000 [03:43<12:09:07, 44.01s/it]

fail data: 5 1 14 [[14, -40.369525307685684, -17.896500875123778, 99, 0, 0, 0, 0.9, 0.9, 0.9]]


  1%|          | 7/1000 [04:16<11:04:46, 40.17s/it]

Success have collected 5 datas


  1%|          | 8/1000 [04:47<10:19:40, 37.48s/it]

Success have collected 6 datas


  1%|          | 9/1000 [05:19<9:50:45, 35.77s/it] 

Success have collected 7 datas


  1%|          | 10/1000 [05:50<9:26:23, 34.33s/it]

Success have collected 8 datas


  1%|          | 11/1000 [06:21<9:09:25, 33.33s/it]

Success have collected 9 datas


  1%|          | 12/1000 [06:52<8:52:39, 32.35s/it]

Success have collected 10 datas


  1%|▏         | 13/1000 [07:23<8:45:41, 31.96s/it]

Success have collected 11 datas


  1%|▏         | 14/1000 [07:52<8:33:56, 31.27s/it]

Success have collected 12 datas


  2%|▏         | 15/1000 [08:23<8:29:46, 31.05s/it]

Success have collected 13 datas


  2%|▏         | 16/1000 [08:54<8:28:11, 30.99s/it]

Success have collected 14 datas


  2%|▏         | 17/1000 [09:24<8:23:14, 30.72s/it]

Success have collected 15 datas


  2%|▏         | 18/1000 [09:56<8:29:41, 31.14s/it]

Success have collected 16 datas


  2%|▏         | 19/1000 [10:27<8:27:17, 31.03s/it]

Success have collected 17 datas


  2%|▏         | 20/1000 [10:58<8:26:23, 31.00s/it]

Success have collected 18 datas


  2%|▏         | 21/1000 [11:29<8:26:52, 31.06s/it]

Success have collected 19 datas


  2%|▏         | 22/1000 [12:01<8:30:52, 31.34s/it]

Success have collected 20 datas


  2%|▏         | 23/1000 [12:32<8:29:46, 31.31s/it]

Success have collected 21 datas


  2%|▏         | 24/1000 [13:03<8:29:36, 31.33s/it]

Success have collected 22 datas


  2%|▎         | 25/1000 [13:34<8:23:38, 30.99s/it]

Success have collected 23 datas


  3%|▎         | 26/1000 [14:06<8:30:56, 31.47s/it]

Success have collected 24 datas


  3%|▎         | 26/1000 [14:26<9:00:55, 33.32s/it]


KeyboardInterrupt: 

In [4]:
sim.genObjs(n=1,ids=14,h=sim.desk_height,handSide='Right')

[[14, -37.90336693106591, -4.751623455940539, 99, 0, 0, 0, 0.9, 0.9, 0.9]]

In [3]:
(sim.objs.ID==0).any()

False

In [1]:
joints=[1.8061175069306046e-05,-98.61856842041016,4.662295341491699,-1.788636326789856,-1.789079189300537,-1.7891252040863037,
                        -1.7886359691619873,-1.7890788316726685,-1.7891250848770142,-1.7886145114898682,-1.789078712463379,-1.7891266345977783,
                        -1.7886520624160767,-1.78908371925354,-1.7891193628311157,-52.2512092590332,21.009044647216797,-2.2276458740234375,
                        -2.230302333831787,30.00031089782715,6.811821460723877,22.398529052734375,-0.8751718401908875,0.14142996072769165,
                        -0.007084177806973457,35.264503479003906,-0.0020231136586517096,5.13994054927025e-05,-100.19393157958984,-4.168997287750244,
                        -2.1731982231140137,-2.1735899448394775,-2.173584222793579,-2.1731984615325928,-2.1735899448394775,-2.173584461212158,
                        -2.173130512237549,-2.1735763549804688,-2.173611640930176,-2.1731984615325928,-2.1735899448394775,-2.173584461212158,
                        -51.53587341308594,-21.0319881439209,-1.1483358144760132,-1.1480298042297363,30.00035858154297,-5.126368522644043,-25.800668716430664]

In [ ]:
joints [16.78989792 36.76516342 40.62049866  4.92565489 20.03301239]

In [70]:
import numpy as np
loaded_array = np.load(r'D:\Deon\Project\robotic_manipulation\tmp\0172_True_NFCJuice.pkl.npy')


In [68]:
loaded_array[-1][[-4,-10,-9,-8,-7]]

array([22.95454979, 36.06108093, 42.06237793,  8.74307919, 23.1450386 ])

In [39]:
sim.EnableEndPointCtrl(False)

In [72]:
data=loaded_array[-1][:]
data[-4]=3.86
data[[-10,-9,-8,-7]]=2.58
sim.changeJoints(data)

In [80]:
sim.getJoints('name')

['joint_knee',
 'joint_left_elbow_pitch',
 'joint_left_elbow_yaw',
 'joint_left_index1',
 'joint_left_index2',
 'joint_left_index3',
 'joint_left_middle1',
 'joint_left_middle2',
 'joint_left_middle3',
 'joint_left_pinky1',
 'joint_left_pinky2',
 'joint_left_pinky3',
 'joint_left_ring1',
 'joint_left_ring2',
 'joint_left_ring3',
 'joint_left_shoulder_pitch',
 'joint_left_shoulder_roll',
 'joint_left_thumb1',
 'joint_left_thumb2',
 'joint_left_wrist_pitch',
 'joint_left_wrist_roll',
 'joint_left_wrist_yaw',
 'joint_lumbar_pitch',
 'joint_lumbar_roll',
 'joint_lumbar_yaw',
 'joint_neck_pitch',
 'joint_neck_roll',
 'joint_neck_yaw',
 'joint_right_elbow_pitch',
 'joint_right_elbow_yaw',
 'joint_right_index1',
 'joint_right_index2',
 'joint_right_index3',
 'joint_right_middle1',
 'joint_right_middle2',
 'joint_right_middle3',
 'joint_right_pinky1',
 'joint_right_pinky2',
 'joint_right_pinky3',
 'joint_right_ring1',
 'joint_right_ring2',
 'joint_right_ring3',
 'joint_right_shoulder_pitch',
 

In [81]:
loaded_array[-1][[-4,-10,-9,-8,-7]]

array([3.86, 2.58, 2.58, 2.58, 2.58])

In [82]:
sim.changeJoints(loaded_array[-1])

In [74]:
np.array(sim.getActuators())[[-4,-10,-9,-8,-7]]

array([4.77578068, 2.27311063, 2.27873397, 2.24340868, 2.26003575])

In [40]:
for data in loaded_array:
    sim.changeJoints(data)
    time.sleep(0.2)
    # print(data[[-4,-10,-9,-8,-7]])

In [60]:
data[[-4,-10,-9,-8,-7]]=4
sim.changeJoints(data)

In [61]:
np.array(sim.getActuators())[[-4,-10,-9,-8,-7]]

array([3.17901635, 2.05018806, 2.05136538, 2.04547381, 2.04775929])

In [27]:
sim.changeJoints(sim.getActuators())

In [29]:
np.array(sim.getActuators())[[-4,-10,-9,-8,-7]]

array([22.9348278 , 16.51228714, 19.19421959,  4.30069923, 10.73864746])

In [34]:
np.array(sim.getActuators())[[[-4,-10,-9,-8,-7]]]

array([[22.93483353, 16.12371254, 18.80642128,  3.91173148, 10.34875488]])

In [65]:
acts = sim.getActuatorRanges()
names=[]
for act in acts:
    names.append(act['name'])

In [114]:
import pickle
with open('../../tmp/trajectory.pkl','rb') as f:
    data = pickle.load(f)

In [117]:
for frame in data[2]['track']:
    print(frame)

[  0.08929926   0.2913778   -1.498201     0.08929926   0.2913778
  -1.498201   -11.434574  ]
[  0.0152624   0.31906    -1.501541    0.0152624   0.31906    -1.501541
 -11.430191 ]
[  0.0152506   0.3205973  -1.4966933   0.0152506   0.3205973  -1.4966933
 -11.445543 ]
[  0.07973564   0.43926048  -1.4980642    0.07973564   0.43926048
  -1.4980642  -11.477306  ]
[ -0.02264699   0.5446808   -1.5046234   -0.02264699   0.5446808
  -1.5046234  -11.47056   ]
[ -0.03282278   0.6122894   -1.4996129   -0.03282278   0.6122894
  -1.4996129  -11.429084  ]
[ 3.6843754e-03  7.5775707e-01 -1.5007132e+00  3.6843754e-03
  7.5775707e-01 -1.5007132e+00 -1.1436306e+01]
[  0.15051174   0.61618197  -1.492411     0.15051174   0.61618197
  -1.492411   -11.454225  ]
[  0.3219349   0.5590512  -1.4996198   0.3219349   0.5590512  -1.4996198
 -11.4496765]
[  0.28420648   0.8405931   -1.4853522    0.28420648   0.8405931
  -1.4853522  -11.441597  ]
[  0.11627597   0.82873356  -1.494217     0.11627597   0.82873356
  -1.4